# Generated by Django 4.2.4 on 2023-08-12 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(default='trainer/teacher.png', upload_to='trainer')),
                ('twitter', models.CharField(default='#', max_length=255)),
                ('facebook', models.CharField(default='#', max_length=255)),
                ('instagram', models.CharField(default='#', max_length=255)),
                ('linkdin', models.CharField(default='#', max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(to='courses.skills')),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(default='course/default.jpg', upload_to='course')),
                ('status', models.BooleanField(default=True)),
                ('counted_view', models.IntegerField()),
                ('counted_like', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('cg', models.ManyToManyField(to='courses.category')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.trainers')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
